Repository Co-Run-Toy-Project/costagram, pull requests merged in 2023-01, with the labels that each got.

#20 💄[ui] 로그인페이지, 게시물 페이지 퍼블리싱 완료 및 아이콘 추가
  client/src/assets/CarouselData.tsx
  client/src/assets/CloudyIcon.tsx
  client/src/assets/DeleteIcon.tsx
  client/src/assets/Logo.tsx
  client/src/assets/PenIcon.tsx
  client/src/assets/RainIcon.tsx
  client/src/assets/SnowIcon.tsx
  client/src/assets/SunnyIcon.tsx
  client/src/assets/kakakoLogo.png
  client/src/assets/logoIcon.png
  client/src/components/PostBox.tsx
  client/src/components/TopBtn.tsx
  client/src/pages/Login/Login.tsx
Labels: styles

#23 💄 [ui] 게시글 및 댓글 퍼블리싱 구현
  client/.eslintrc.ts
  client/package.json
  client/src/assets/HeartOff.tsx
  client/src/assets/HeartOn.tsx
  client/src/assets/SearchIcon.tsx
  client/src/components/BoardContent.tsx
  client/src/components/LikeComp.tsx
  client/src/components/ReviewContainer.tsx
  client/src/components/SearchComp.tsx
  client/src/components/reuse/BoardContainer.tsx
  client/yarn.lock
Labels: feat, styles, 성훈

#22 💄 [ui] 모달(post, confirm), navbar 퍼블리싱
  client/src/assets/UploadPhotoIcon.tsx
  client/src/components/CancelModal.tsx
  client/src/components/Navbar.tsx
  client/src/components/PostModal.tsx
  client/src/components/reuse/ModalButton.tsx
  client/src/components/reuse/Navbar.tsx
  client/src/pages/Main/Main.tsx
  client/src/recoil/modalAtom.tsx
Labels: styles, 은비

#24 ✨[feat] 라우팅 구현, 스키마 생성
  server/.babelrc
  server/.eslintrc
  server/.gitignore
  server/.gitmessage.txt
  server/.prettierrc
  server/config/index.ts
  server/index.js
  server/models/like.js
  server/models/post.js
  server/models/user.js
  server/package-lock.json
  server/package.json
  server/routes/comment.js
  server/routes/index.js
  server/routes/like.js
  server/routes/post.js
  server/routes/user.js
Labels: feat, 오은

#25 [💄 UI] 마이페이지 ui 구현
  client/public/images.jpg
  client/src/pages/MyPage/MyPage.tsx
Labels: styles, 담은

#31 🐛 [Bugfix] tailwind prettier plugin 관련 이슈 해결
  client/.eslintrc.ts
  client/.prettierrc
  client/.prettierrc.js
  client/.yarn/cache/prettier-plugin-tailwindcss-npm-0.2.1-848c29a572-5a04b26f50.zip
  client/.yarn/install-state.gz
  client/package.json
  client/src/App.tsx
  client/src/assets/Logo.tsx
  client/src/components/Navbar.tsx
  client/src/components/PostModal.tsx
  client/yarn.lock
Labels: bugFix

#27 ✨[feat] 서버 상태 코드 및 더미데이터
  server/index.js
  server/package.json
  server/routes/comment.js
  server/routes/post.js
  server/routes/user.js
Labels: feat, 오은

#38 ✨[feat] 게시물 컨트롤러 구현
  server/controller/postController.js
  server/index.js
  server/models/connectDB.js
  server/models/post.js
  server/models/schema/comment.js
  server/models/schema/like.js
  server/models/schema/post.js
  server/models/schema/profile.js
  server/models/schema/user.js
  server/package-lock.json
  server/package.json
  server/routes/post.js
Labels: feat, 오은

#45 ✨ [Feat] 게시글 get 요청 기능 구현
  client/.eslintrc.json
  client/.eslintrc.ts
  client/.yarn/cache/@types-axios-npm-0.14.0-42f41917ea-12a230b940.zip
  client/.yarn/cache/axios-npm-1.2.2-151da260f0-6e357491b3.zip
  client/.yarn/cache/form-data-npm-4.0.0-916facec2d-01135bf867.zip
  client/.yarn/cache/proxy-from-env-npm-1.1.0-c13d07f26b-ed7fcc2ba0.zip
  client/.yarn/install-state.gz
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/apis/post/deletePost.tsx
  client/src/apis/post/getPosts.tsx
  client/src/apis/post/patchPost.tsx
  client/src/assets/HeartOn.tsx
  client/src/assets/HomeIcon.tsx
  client/src/assets/Logo.tsx
  client/src/components/PostModal.tsx
  client/src/components/RenderPosts.tsx
  client/src/components/reuse/PostBox.tsx
  client/src/hooks/post/useDeletePost.tsx
  client/src/hooks/post/useGetPost.tsx
  client/src/hooks/post/usePatchPost.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/MyPage/MyPage.tsx
  client/tsconfig.json
  client/yarn.lock
Labels: feat, 은비

#47 💄 [ui] 게시물 퍼블리싱 합치기 , 캐러셀 구현
  client/src/components/BoardContent.tsx
  client/src/components/Carousel.tsx
  client/src/components/SearchComp.tsx
  client/src/components/reuse/BoardContainer.tsx
  client/src/components/reuse/PostBox.tsx
  client/tailwind.config.js
  server/package.json
Labels: styles, 여울

#48 🐛 [Bugfix] daisyui 재설치
  client/package.json
  server/package-lock.json
  server/package.json
Labels: bugFix, 여울

#51 ✨[feat] 댓글 등록 컨트롤러 구현 및 게시물 컨트롤러와 연결
  server/controller/commentController.js
  server/controller/postController.js
  server/index.js
  server/models/schema/comment.js
  server/models/schema/post.js
  server/routes/comment.js
  server/routes/post.js
Labels: feat, 오은

#52 💄 [ui] Kakao 로그인버튼 ui 수정
  client/src/assets/kakao_login_medium_narrow.png
  client/src/pages/Login/Login.tsx
  client/yarn.lock
Labels: bugFix, styles, 성훈

#54 ✨[feat] 카카오 로그인 유저 정보 조회 구현
  server/controller/authController.js
  server/index.js
  server/package-lock.json
  server/package.json
  server/routes/auth.js
  server/utils/kakaoInstance.js
Labels: feat, 오은

#55 🐛 [Bugfix] eslint 에러 해결, top버튼 스크롤 수정
  client/src/components/Carousel.tsx
  client/src/components/TopBtn.tsx
  client/src/components/reuse/PostBox.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Main/Main.tsx
Labels: bugFix, 여울

#56 ✨ [feat] oauth 인가코드 요청 구현
  client/.gitignore
  client/package.json
  client/src/components/OauthRedirectHandler.tsx
  client/src/pages/Login/Login.tsx
  client/src/recoil/oauthAtom.tsx
  client/src/router/Router.tsx
  client/yarn.lock
Labels: feat, 성훈

#58 ✨[feat] 게시물 & 댓글 컨트롤러 구현 및 리팩토링
  server/controller/commentController.js
  server/controller/postController.js
  server/models/schema/comment.js
  server/models/schema/post.js
  server/routes/post.js
Labels: feat, 오은

#59 ✨[feat] kakao oauth 인가코드 백엔드 서버로 전달로직 구현완료
  client/src/apis/post/get/getOauth.tsx
  client/src/components/OauthRedirectHandler.tsx
  client/src/hooks/get/useGetOauth.tsx
  client/src/pages/Login/Login.tsx
  client/yarn.lock
Labels: feat, 성훈

#60 ✨[feat] 회원 가입 및 로그인, 토큰 생성 기능 구현
  server/controller/authController.js
  server/models/schema/post.js
  server/models/schema/user.js
  server/package-lock.json
  server/package.json
  server/utils/jwt.js
  server/utils/kakaoInstance.js
Labels: feat, 오은

#64 [feat]지도 API 추가, 마이 페이지 구현 완료
  client/public/index.html
  client/src/apis/user/getUser.tsx
  client/src/components/MakeMap.tsx
  client/src/components/PostModal.tsx
  client/src/hooks/user/useGetUser.tsx
  client/src/pages/MyPage/MyPage.tsx
  client/src/pages/MyPage/MyPagePic.tsx
  client/src/pages/MyPage/MyPageProfile.tsx
  client/src/react-app-env.d.ts
  client/src/recoil/modalAtom.tsx
Labels: feat, 담은

#66 ✨[feat] 토큰 수정 및 프로필 컨트롤러 구현
  server/controller/authController.js
  server/controller/userController.js
  server/routes/user.js
Labels: feat, 오은

#68 ✨[feat] 게시물 수정 기능에 위치 정보 추가
  server/controller/postController.js
Labels: feat, 오은

#70 ✨[feat] 무한스크롤 구현, 캐러셀 버튼 조건부 설정
  client/package.json
  client/src/assets/CarouselData.tsx
  client/src/assets/CloudyIcon.tsx
  client/src/assets/RainIcon.tsx
  client/src/assets/SnowIcon.tsx
  client/src/assets/SunnyIcon.tsx
  client/src/assets/WeatherIcon.tsx
  client/src/components/Carousel.tsx
  client/src/components/Loading.tsx
  client/src/components/RenderPosts.tsx
  client/src/components/reuse/PostBox.tsx
  client/src/pages/Main/Main.tsx
Labels: feat, styles, 여울

#79 ✨[feat] 댓글 조회 구현, 게시물 개별 조회 수정
  server/controller/commentController.js
  server/controller/postController.js
  server/routes/post.js
Labels: feat, 오은

#78 ✨ [feat] 로그인여부에 따른 Nav바 조건부랜더링
  client/src/components/Navbar.tsx
  client/src/components/OauthRedirectHandler.tsx
  client/src/components/SearchComp.tsx
  client/src/hooks/get/useGetOauth.tsx
  client/src/pages/Login/Login.tsx
  client/src/recoil/oauthAtom.tsx
  client/yarn.lock
Labels: feat, 성훈

#72 [fix] 카카오맵 오류 수정 및 마이페이지 수정
  client/src/components/MakeMap.tsx
  client/src/components/PostModal.tsx
  client/src/pages/MyPage/MyPagePic.tsx
  client/src/pages/MyPage/MyPageProfile.tsx
Labels: bugFix, 담은

#84 ✨[feat] 토큰 적용, 에러 처리, 개수, 좋아요 구현
  server/controller/authController.js
  server/controller/commentController.js
  server/controller/likeController.js
  server/controller/postController.js
  server/controller/userController.js
  server/index.js
  server/models/schema/comment.js
  server/models/schema/like.js
  server/models/schema/post.js
  server/models/schema/user.js
  server/routes/auth.js
  server/routes/post.js
  server/routes/user.js
  server/utils/JwtMiddleware.js
  server/utils/jwt.js
Labels: feat, 오은

#83 [feat] 카카오맵 현재 주소 가져오기 기능 추가, 날씨 API 연결, 사진 여러장 추가 기능, 포스팅 기능 추가
  client/public/index.html
  client/src/apis/user/getUser.tsx
  client/src/apis/weather/getWeather.tsx
  client/src/components/MakeMap.tsx
  client/src/components/PostCarousel.tsx
  client/src/components/PostModal.tsx
  client/src/hooks/post/useCreatePost.tsx
  client/src/hooks/weather/useGetWeather.tsx
  client/src/pages/MyPage/MyPage.tsx
  client/src/recoil/modalAtom.tsx
Labels: bugFix, feat, 담은

#86 ✨ [Feat] 수정모달 수정, 헤더 토큰 추가 , 댓글 Read 구현
  client/src/apis/posts/deletePost.tsx
  client/src/apis/posts/getPostById.tsx
  client/src/apis/posts/getPosts.tsx
  client/src/apis/posts/patchPost.tsx
  client/src/apis/weather/getWeather.tsx
  client/src/components/ModifyModal.tsx
  client/src/components/Navbar.tsx
  client/src/components/ReviewContainer.tsx
  client/src/components/reuse/BoardContainer.tsx
  client/src/components/reuse/PostBox.tsx
  client/src/components/reuse/Review.tsx
  client/src/hooks/posts/useGetPostById.tsx
  client/src/hooks/posts/usePatchPost.tsx
  client/src/pages/Main/Main.tsx
  client/src/recoil/postAtom.tsx
Labels: feat, 은비

#88 ✨ [feat] 댓글 추가, 삭제 기능 및 로그인 여부에 따른 navbar 변경 기능 구현
  client/src/apis/review/deleteReview.tsx
  client/src/apis/review/postReview.tsx
  client/src/assets/HeartOff.tsx
  client/src/assets/HeartOn.tsx
  client/src/components/Navbar.tsx
  client/src/components/OauthRedirectHandler.tsx
  client/src/components/RenderPosts.tsx
  client/src/components/ReviewContainer.tsx
  client/src/components/SearchComp.tsx
  client/src/components/reuse/BoardContainer.tsx
  client/src/components/reuse/PostBox.tsx
  client/src/components/reuse/Review.tsx
  client/src/hooks/get/useGetOauth.tsx
  client/src/hooks/review/useDeleteReview.tsx
  client/src/hooks/review/usePostReview.tsx
  client/yarn.lock
Labels: bugFix, feat, 성훈

#89 [feat]post 기능 최종 파일
  client/src/apis/weather/getWeather.tsx
  client/src/components/PostModal.tsx
  client/src/hooks/post/useCreatePost.tsx
Labels: bugFix, 담은

#91 ✨[feat] 마이페이지에서 유저가 올린 게시물을 확인한다. && 페이지네이션
  server/controller/commentController.js
  server/controller/postController.js
  server/controller/userController.js
  server/models/schema/comment.js
  server/models/schema/post.js
  server/models/schema/user.js
Labels: bugFix, feat, 오은

#93 [feat]마이페이지 덧글 및 좋아요 숫자 표시
  client/src/apis/weather/getWeather.tsx
  client/src/assets/HeartOn.tsx
  client/src/components/PostModal.tsx
  client/src/pages/MyPage/MyPage.tsx
  client/src/pages/MyPage/MyPagePic.tsx
Labels: feat, 담은

#96 🐛 [Bug] 게시물 수정 버그 해결
  server/controller/postController.js
  server/package-lock.json
  server/package.json
Labels: bugFix, 오은
