Repository Co-Run-Toy-Project/costagram, pull requests merged in 2023-02, with the labels that each got.

#97 ✨ [Feat] Modal 기능 수정
  client/.yarn/install-state.gz
  client/src/assets/AddIcon.tsx
  client/src/assets/BasicUserImage.tsx
  client/src/assets/MagnifyIcon.tsx
  client/src/assets/PenIcon.tsx
  client/src/components/ModifyModal.tsx
  client/src/components/Navbar.tsx
  client/src/components/PostModal.tsx
  client/src/components/RenderPosts.tsx
  client/src/components/reuse/PostBox.tsx
  client/src/hooks/posts/usePatchPost.tsx
  client/yarn.lock
Labels: feat, 은비

#99 ✨ [Feat] 마이페이지 소개글 수정 기능 구현
  client/.eslintrc.json
  client/src/apis/user/patchDes.tsx
  client/src/assets/PenIcon.tsx
  client/src/components/Navbar.tsx
  client/src/hooks/user/usePatchDes.tsx
  client/src/pages/MyPage/MyPageProfile.tsx
Labels: feat, 은비

#100 [feat]마이페이지 반응형 수정, 모달 닫을시 내용 초기화
  client/src/assets/PenIcon.tsx
  client/src/components/PostModal.tsx
  client/src/pages/MyPage/MyPagePic.tsx
  client/src/pages/MyPage/MyPageProfile.tsx
Labels: feat, styles, 담은

#103 ✨ [Feat] 테스트 계정을 생성한다
  server/controller/authController.js
  server/index.js
  server/routes/demo.js
Labels: feat, 오은

#105 ✨[feat] 검색 기능을 구현한다
  server/controller/postController.js
  server/routes/index.js
  server/routes/like.js
  server/routes/post.js
Labels: feat, 오은

#107 🐛[fix] 토큰 에러 수정
  server/controller/authController.js
Labels: bugFix, 오은

#108 마이페이지 여백 조절 수정
  client/src/pages/MyPage/MyPageProfile.tsx
Labels: styles, 담은

#109 ✨ [Feat] 검색 기능 구현
  client/src/apis/posts/postSortPosts.tsx
  client/src/apis/testUser/getTestLogin.tsx
  client/src/apis/weather/getWeather.tsx
  client/src/assets/BasicUserImage.tsx
  client/src/assets/HomeIcon.tsx
  client/src/assets/Logo.tsx
  client/src/components/ModifyModal.tsx
  client/src/components/Navbar.tsx
  client/src/components/PostModal.tsx
  client/src/components/RenderPosts.tsx
  client/src/components/reuse/PostBox.tsx
  client/src/components/reuse/Review.tsx
  client/src/hooks/posts/useCreatePost.tsx
  client/src/hooks/posts/usePostSortPosts.tsx
  client/src/hooks/testUser/useGetTestLogin.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/MyPage/MyPageProfile.tsx
  client/src/recoil/postAtom.tsx
Labels: feat

#113 ✨[feat] 이미지를 S3에 업로드하고 링크를 반환한다
  client/src/hooks/posts/useCreatePost.tsx
  server/controller/postController.js
  server/routes/post.js
  server/utils/UploadS3.js
Labels: feat, 오은

#114 🎨[structure] aws-sdk 설치
  server/package-lock.json
  server/package.json
Labels: 오은

#110 ✨ [feat] 무한스크롤 구현 #9
  README.md
  client/src/components/Carousel.tsx
  client/src/components/RenderPosts.tsx
Labels: feat

#116 ✨ [feat] 캐러셀 s3 imagePath 연결 #115
  client/src/components/Carousel.tsx
  client/src/components/reuse/PostBox.tsx
Labels: feat

#120 ✨[feat] 마이페이지 레이아웃을 수정한다
  client/src/pages/MyPage/MyPagePic.tsx
Labels: 오은, develop

#127 🔥[remove] crypto 패키지를 삭제합니다
  server/package-lock.json
  server/package.json
Labels: bugFix, 오은

#128 🐛 [fix] 캐러셀, 게시물중복렌더 버그 해결 #121 #124
  client/src/components/Carousel.tsx
  client/src/components/RenderPosts.tsx
Labels: bugFix

#129 ♻️[refactor] 위치 기본값을 수정한다
  server/models/schema/post.js
Labels: feat, 오은

#132 ✨[feat] 캐러셀 구현
  client/src/assets/LeftIcon.tsx
  client/src/assets/RightIcon.tsx
  client/src/components/Carousel.tsx
  client/src/components/ImageCarousel.tsx
  client/src/components/reuse/PostBox.tsx
Labels: bugFix, 오은, develop

#134 🐛[fix] 이미지가 교체되도록 수정한다
  client/src/components/PostModal.tsx
Labels: bugFix, 오은

#136 ✨ [Feat] 좋아요 기능 api 작성
  client/src/apis/likes/putLikes.tsx
  client/src/assets/costagramLogo.png
  client/src/components/BoardContent.tsx
  client/src/components/LikeComp.tsx
  client/src/components/Navbar.tsx
  client/src/components/reuse/BoardContainer.tsx
  client/src/components/reuse/PostBox.tsx
  client/src/hooks/likes/usePutLikes.tsx
  server/package-lock.json
Labels: 은비

#137 ✨ [Feat] 더보기 기능을 구현한다
  client/src/components/BoardContent.tsx
  client/src/components/LikeComp.tsx
Labels: 오은, develop

#138 ♻️[refactor] 이미지 S3 버킷 변경
  server/utils/UploadS3.js
Labels: bugFix, 오은

#139 🐛[fix] eslint 에러 해결
  client/src/assets/HeartOn.tsx
  client/src/components/BoardContent.tsx
Labels: bugFix, 오은

#141 ✨ [Feat] 캐러셀 버튼 크기를 수정합니다
  client/src/assets/LeftIcon.tsx
  client/src/assets/RightIcon.tsx
  client/src/components/ImageCarousel.tsx
Labels: styles, 오은

#143 💄[ui] 마이페이지의 레이아웃을 수정한다
  client/src/assets/HeartIcon.tsx
  client/src/assets/SearchIcon.tsx
  client/src/pages/MyPage/MyPage.tsx
  client/src/pages/MyPage/MyPagePic.tsx
Labels: styles, 오은, develop

#147 ✨[feat] AWS S3에 배포 자동화한다
  .github/workflows/client-deploy.yml
Labels: feat, 오은

#148 💄[ui] 더 보기 태그를 수정한다
  client/src/components/BoardContent.tsx
Labels: styles, 오은

#149 🐛[fix] Github Actions를 수정한다
  .github/workflows/client-deploy.yml
Labels: bugFix, 오은

#151 🐛[fix] Github Actions 스크립트를 수정한다
  .github/workflows/client-deploy.yml
Labels: bugFix, 오은

#152 🐛[fix] 무한스크롤 에러를 수정합니다
  client/src/apis/posts/getPosts.tsx
  client/src/components/RenderPosts.tsx
  client/src/hooks/posts/useGetPost.tsx
  client/src/hooks/posts/useIntersectionObserver.tsx
Labels: 오은, develop
